/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./*.html"],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
              "outline": "#737686",
              "surface-container-highest": "#e1e3e4",
              "surface-dim": "#d9dadb",
              "on-tertiary-container": "#e4f2ff",
              "on-secondary-container": "#54647a",
              "background": "#f8f9fa",
              "tertiary-fixed-dim": "#89ceff",
              "primary-container": "#2563eb",
              "on-primary-container": "#eeefff",
              "surface-container-low": "#f3f4f5",
              "surface-container-high": "#e7e8e9",
              "on-surface": "#191c1d",
              "on-error-container": "#93000a",
              "surface-container": "#edeeef",
              "surface-variant": "#e1e3e4",
              "on-primary": "#ffffff",
              "secondary-fixed": "#d3e4fe",
              "on-tertiary-fixed": "#001e2f",
              "secondary-fixed-dim": "#b7c8e1",
              "secondary-container": "#d0e1fb",
              "inverse-surface": "#2e3132",
              "tertiary-fixed": "#c9e6ff",
              "on-secondary-fixed": "#0b1c30",
              "on-secondary-fixed-variant": "#38485d",
              "surface": "#f8f9fa",
              "on-primary-fixed": "#00174b",
              "on-secondary": "#ffffff",
              "on-error": "#ffffff",
              "on-background": "#191c1d",
              "surface-tint": "#0053db",
              "surface-bright": "#f8f9fa",
              "tertiary": "#005a82",
              "secondary": "#505f76",
              "tertiary-container": "#0074a6",
              "primary-fixed": "#dbe1ff",
              "surface-container-lowest": "#ffffff",
              "error": "#ba1a1a",
              "error-container": "#ffdad6",
              "primary": "#004ac6",
              "outline-variant": "#c3c6d7",
              "on-tertiary": "#ffffff",
              "inverse-on-surface": "#f0f1f2",
              "on-tertiary-fixed-variant": "#004c6e",
              "on-primary-fixed-variant": "#003ea8",
              "on-surface-variant": "#434655",
              "primary-fixed-dim": "#b4c5ff",
              "inverse-primary": "#b4c5ff"
      },
      "borderRadius": {
              "DEFAULT": "0.25rem",
              "lg": "0.5rem",
              "xl": "0.75rem",
              "full": "9999px"
      },
      "spacing": {
              "section-gap": "40px",
              "margin-mobile": "16px",
              "gutter": "24px",
              "sidebar-width": "260px",
              "stack-gap": "12px",
              "container-max-width": "1200px"
      },
      "fontFamily": {
              "body-lg": ["Hanken Grotesk", "sans-serif"],
              "headline-lg-mobile": ["Hanken Grotesk", "sans-serif"],
              "body-sm": ["Hanken Grotesk", "sans-serif"],
              "label-sm": ["Hanken Grotesk", "sans-serif"],
              "headline-md": ["Hanken Grotesk", "sans-serif"],
              "headline-xl": ["Hanken Grotesk", "sans-serif"],
              "label-md": ["Hanken Grotesk", "sans-serif"],
              "headline-lg": ["Hanken Grotesk", "sans-serif"],
              "body-md": ["Hanken Grotesk", "sans-serif"]
      },
      "fontSize": {
              "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
              "headline-lg-mobile": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
              "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
              "label-sm": ["12px", {"lineHeight": "16px", "fontWeight": "500"}],
              "headline-md": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
              "headline-xl": ["36px", {"lineHeight": "44px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
              "label-md": ["14px", {"lineHeight": "20px", "fontWeight": "600"}],
              "headline-lg": ["28px", {"lineHeight": "36px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
              "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}
