const fs=require('fs'),vm=require('vm'),assert=require('assert/strict'),M=require('../js/floor-plan-model');
const source=fs.readFileSync('js/floor-plan-rack-master.js','utf8'),headers=['랙타입코드','랙타입명','베이폭(m)','깊이(m)','전체높이(m)','단수','단당높이(m)','깊이수'];
function environment(mode){let posts=0,rows=[['OLD','같은 이름',2,1,6,4,1.5,1]],listeners={},row;const window={WmsFloorPlanModel:M,WMS_RACK_MASTER_CONFIG:{clientId:'test',spreadsheetId:'verified-id',sheetName:'랙타입 마스터',sheetId:100867756},google:{accounts:{oauth2:{initTokenClient:o=>({requestAccessToken:()=>o.callback({access_token:'TOKEN',expires_in:300})})}}},addEventListener:(k,f)=>listeners[k]=f};const fetch=async(url,options)=>{const response=values=>({ok:true,json:async()=>values});if(options.method==='POST'){posts++;row=JSON.parse(options.body).values[0];if(mode==='forbidden')return {ok:false,status:403};if(mode==='lost-success'){rows.push(row);throw Error('connection lost');}if(mode==='unknown')throw Error('connection lost');rows.push(row);return response({updates:{updatedRows:1,updatedRange:"'랙타입 마스터'!A6:H6"}});}const range=decodeURIComponent(url.split('/values/')[1]?.split('?')[0]||'');if(!range)return response({sheets:[{properties:{sheetId:100867756,title:'랙타입 마스터',gridProperties:{rowCount:1001}}}]});if(/A4:[HL]4$/.test(range))return response({values:[mode==='header-change'?['Wrong']:headers]});if(mode==='readback-failure'&&posts)throw Error('connection lost');return response({values:range.endsWith('A6:H6')?[row]:rows});};vm.runInNewContext(source,{window,fetch,Intl,Date,crypto:require('crypto').webcrypto,document:{},Error,Promise});return {api:window.WmsRackMaster,posts:()=>posts,rows:()=>rows};}
(async()=>{const type=M.presets()[1];let e=environment('normal'),name;const result=await e.api.save(type,'같은 이름',{canWrite:()=>true,onName:n=>name=n});assert.match(name,/^같은 이름 \d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}$/);assert.equal(result.name,name);assert.equal(e.posts(),1);assert.deepEqual(e.rows()[0],['OLD','같은 이름',2,1,6,4,1.5,1]);
e=environment('normal');const explicit=await e.api.save(type,'새 이름',{code:' my-rack-01 ',canWrite:()=>true});assert.equal(explicit.id,'MY-RACK-01');assert.equal(e.rows()[1][0],'MY-RACK-01');assert.equal(e.posts(),1);
e=environment('normal');await assert.rejects(e.api.save(type,'같은 이름',{code:' old ',canWrite:()=>true}),err=>err.duplicateCode===true);assert.equal(e.posts(),0);assert.equal(e.rows().length,1);
for(const code of ['', '한글', 'INVALID CODE', '=FORMULA', 'A'.repeat(25)]){e=environment('normal');await assert.rejects(e.api.save(type,'새 이름',{code,canWrite:()=>true}),/1~24/);assert.equal(e.posts(),0);}
e=environment('normal');const generated=e.api.generateCode();assert.match(generated,/^RACK-[A-Z0-9]+-[A-F0-9]{6}$/);assert.equal(e.api.validateCode(generated),generated);
e=environment('header-change');await assert.rejects(e.api.save(type,'새 이름',{canWrite:()=>true}),/열 구성/);assert.equal(e.posts(),0);
e=environment('forbidden');await assert.rejects(e.api.save(type,'새 이름',{canWrite:()=>true}),/편집 권한/);assert.equal(e.posts(),1);
e=environment('lost-success');await e.api.save(type,'새 이름',{canWrite:()=>true});assert.equal(e.posts(),1);assert.equal(e.rows().length,2);
for(const mode of ['unknown','readback-failure']){e=environment(mode);await assert.rejects(e.api.save(type,'새 이름',{canWrite:()=>true}),err=>err.uncertain===true);assert.equal(e.posts(),1);}
e=environment('normal');let checks=0;await assert.rejects(e.api.save(type,'새 이름',{canWrite:()=>++checks===1}),/세션/);assert.equal(e.posts(),0);
console.log('Rack master: correct columns, timestamp, existing row preservation, changed header, denied permission, expired session, interrupted POST recovery and uncertain result passed.');})().catch(e=>{console.error(e);process.exitCode=1;});
