const assert=require('node:assert/strict');
const M=require('../js/floor-plan-model');

const plan=M.blank();
plan.rackTypes=[{id:'CUSTOM03',name:'테스트 랙',bayWidth:1,depth:1,height:10,levels:10,depthCount:1}];
plan.objects=[{id:'W01',kind:'W',x:2,y:2,w:4,h:4,angle:0,rackTypeId:'CUSTOM03',bayGap:0,rowGap:0,locked:false}];
const rack=plan.objects[0],locations=M.generateRackLocations(rack,plan);
assert.equal(locations.cells.length,160);
assert.deepEqual(locations.layout,{bays:4,rows:4,levels:10,depthCount:1});
assert.deepEqual(locations.cells[0],{x:0,y:0,level:1,depth:1,code:'W01-L01-B01-R01'});
assert.deepEqual(locations.cells.at(-1),{x:3,y:3,level:10,depth:1,code:'W01-L10-B04-R16'});
rack.locationPlan=locations;
const saved=M.readFile(JSON.parse(M.serializeFile(plan)));assert.deepEqual(saved.objects[0].locationPlan,locations);
const legacy=M.clone(saved);delete legacy.objects[0].locationPlan.rule.prefixes;for(const cell of legacy.objects[0].locationPlan.cells)cell.code=`W01-B${String(cell.x+1).padStart(2,'0')}-R${String(cell.y+1).padStart(2,'0')}-L${String(cell.level).padStart(2,'0')}`;
assert.equal(M.readFile(JSON.parse(M.serializeFile(legacy))).objects[0].locationPlan.cells[0].code,'W01-B01-R01-L01','기존 .gics의 로케이션 코드를 자동 변경하지 않는다.');
const custom=M.generateRackLocations(rack,plan,{prefixes:{warehouse:'WH',rack:'Z',level:'F',bay:'A',cell:'C'}});
assert.equal(custom.cells[0].code,'WH-Z01-F01-A01-C01');
assert.deepEqual(M.readFile(JSON.parse(M.serializeFile({...plan,objects:[{...rack,locationPlan:custom}]}))).objects[0].locationPlan,custom);
assert.throws(()=>M.generateRackLocations(rack,plan,{prefixes:{cell:'1'}}),/이니셜/);
const changed=M.clone(saved);changed.objects[0].id='W09';assert.equal(M.read(changed).objects[0].locationPlan.cells[0].code,'W01-L01-B01-R01','랙 코드 변경으로 기존 로케이션을 조용히 재지정하지 않는다.');
changed.rackTypes[0].levels=9;assert.ok(M.validate(M.read(changed)).some(issue=>issue.message.includes('랙 규격이 저장된 로케이션과 다릅니다')));
assert.equal(M.read(changed).objects[0].locationPlan.cells.length,160,'규격 변경으로 기존 로케이션을 삭제하지 않는다.');
const reversed=M.generateRackLocations(rack,plan,{startCorner:'bottomRight',firstAxis:'row',levelOrder:'descending'});
assert.deepEqual([reversed.cells[0].x,reversed.cells[0].y,reversed.cells[0].level,reversed.cells[0].code],[3,3,10,'W01-L10-B01-R01']);
const rowFirst=M.generateRackLocations(rack,plan,{firstAxis:'row'});
assert.equal(locations.cells.find(cell=>cell.x===1&&cell.y===0&&cell.level===1).code,'W01-L01-B02-R02');
assert.equal(rowFirst.cells.find(cell=>cell.x===1&&cell.y===0&&cell.level===1).code,'W01-L01-B02-R05');
const topRight=M.generateRackLocations(rack,plan,{startCorner:'topRight'});
assert.equal(topRight.cells.find(cell=>cell.x===0&&cell.y===0&&cell.level===1).code,'W01-L01-B04-R04');
const duplicate=M.clone(saved);duplicate.objects[0].locationPlan.cells[1].code=duplicate.objects[0].locationPlan.cells[0].code;assert.throws(()=>M.read(duplicate),/중복/);
const duplicateAcrossRacks=M.clone(saved);duplicateAcrossRacks.objects.push({...M.clone(duplicateAcrossRacks.objects[0]),id:'W02',x:8});assert.throws(()=>M.read(duplicateAcrossRacks),/로케이션 코드가 중복/);
const depth=M.clone(plan);depth.rackTypes[0].depthCount=2;const depthLocations=M.generateRackLocations(depth.objects[0],depth);assert.equal(depthLocations.cells.length,320);assert.equal(depthLocations.cells[0].code,'W01-L01-B01-R01-D01');assert.equal(depthLocations.cells[1].code,'W01-L01-B01-R01-D02');
console.log('Rack locations: generation order, depth, .gics roundtrip, stable codes, mismatch warning and duplicate guard passed.');
