const assert=require('assert/strict'),fs=require('fs'),vm=require('vm');
const M=require('../js/floor-plan-model');
const p=M.sample(),original=JSON.stringify(p);
assert.equal(M.read(p).objects.length,12);assert.deepEqual(M.validate(p),[]);assert.deepEqual(M.read(JSON.parse(original)),p);
const h=new M.History(p),next=M.clone(p);M.move(next.objects[0],2.123,3.456);h.commit(next);assert.equal(h.plan.objects[0].x,2.123);h.undo();assert.equal(h.plan.objects[0].x,2);h.redo();assert.equal(h.plan.objects[0].y,3.456);assert.equal(JSON.stringify(p),original);
const bad=M.clone(h.plan);bad.objects[0].x=199;assert.throws(()=>h.commit(bad),/경계/);assert.equal(h.plan.objects[0].x,2.123);bad.objects[0].x=2.0001;assert.throws(()=>M.read(bad),/셋째/);
for(const v of[Infinity,NaN,-1,0])assert.throws(()=>M.read({...p,width:v}));
const dupe=M.clone(p);dupe.objects[1].id=dupe.objects[0].id;assert.throws(()=>M.read(dupe),/중복/);
const malicious=M.clone(p);malicious.objects[0].id='<img onerror=alert(1)>';assert.throws(()=>M.read(malicious),/대상 코드/);
const diag=M.blank();diag.objects=[{id:'CV01',kind:'CV',points:[{x:2,y:2},{x:8,y:10},{x:18,y:10}],width:1.5,cap:'butt',locked:false}];M.read(diag);const path=diag.objects[0],pts=M.clone(path.points),length=M.pathLength(path);path.width=.3;assert.equal(M.pathLength(M.read(diag).objects[0]),length);assert.deepEqual(path.points,pts);assert.equal(length,20);
const snap=M.clone(path);for(let i=0;i<4;i++)M.rotate(path);assert.deepEqual(path,snap);
path.points[1]=M.clone(path.points[0]);assert.throws(()=>M.read(diag),/同|같은/);
const legacyPlan=M.read(JSON.parse(fs.readFileSync(require.resolve('./fixtures/floor-plan-v1.json'),'utf8').replace(/^\uFEFF/,'')));const rack={...M.clone(p.objects[0]),rackTypeId:'RACK-01'};Object.assign(rack,{w:10,h:3});let r=M.rackLayout(rack,legacyPlan);assert.deepEqual([r.bays,r.rows,r.floorCells,r.totalCells],[5,3,15,60]);Object.assign(rack,{w:2.46,h:1.23,rackTypeId:'RACK-02'});r=M.rackLayout(rack,legacyPlan);assert.deepEqual([r.bays,r.rows,r.floorCells,r.totalCells,r.remainingW],[2,1,4,16,0]);rack.bayGap=.1;r=M.rackLayout(rack,legacyPlan);assert.equal(r.bays,1);assert.equal(r.remainingW,1.23);rack.w=.5;assert.equal(M.rackLayout(rack,legacyPlan).floorCells,0);rack.angle=90;M.rotate(rack);assert.equal(rack.w,.5);assert.equal(rack.h,1.23);
assert.deepEqual(M.presets(),require('../data/floor-plan-rack-presets.json').rackTypes);assert.equal(p.rackTypes.length,5);const copy=M.presets();copy[0].levels=1;assert.equal(M.presets()[0].levels,10);const sourceRack={...p.objects[0],rackTypeId:'SHELF-5L',w:3,h:1};const sourceCapacity=M.rackLayout(sourceRack,p);assert.deepEqual([sourceCapacity.bays,sourceCapacity.rows,sourceCapacity.floorCells,sourceCapacity.totalCells],[2,2,4,20]);const invalidLevel=M.clone(p);invalidLevel.rackTypes[0].levelHeight=0;assert.throws(()=>M.read(invalidLevel),/단당 높이/);
const diagonal={id:'T01',kind:'T',points:[{x:2,y:2},{x:10,y:10}],width:.3,cap:'butt'},away={id:'B01',kind:'B',x:2,y:8,w:1,h:1,angle:0};assert.ok(M.intersects(M.bounds(diagonal),M.bounds(away)));const collision=M.blank();collision.objects=[diagonal,away];assert.deepEqual(M.validate(M.read(collision)),[],'Diagonal empty bounding-box area is not occupied.');
const tunnel=M.blank();tunnel.objects=[{id:'CV01',kind:'CV',points:[{x:5,y:5},{x:5,y:15}],width:1.5,cap:'butt'},{id:'BT01',kind:'BT',x:0,y:0,w:2,h:1.5,angle:0,conveyorId:'CV01',offset:5}];const bt=tunnel.objects[1];M.alignTunnel(bt,tunnel);assert.equal(bt.angle,90);assert.equal(bt.x+bt.w/2,5);assert.equal(bt.y+bt.h/2,10);assert.deepEqual(M.validate(M.read(tunnel)),[]);bt.h=.3;assert.ok(M.validate(tunnel).some(x=>x.message.includes('폭보다 작')));bt.x++;assert.ok(M.validate(tunnel).some(x=>x.message.includes('위치·방향')));bt.offset=20;assert.throws(()=>M.alignTunnel(bt,tunnel),/전체 길이/);
const flowPlan=M.read(tunnel),flowCv=flowPlan.objects.find(o=>o.kind==='CV'),flowBt=flowPlan.objects.find(o=>o.kind==='BT');assert.equal(M.segmentDirection(flowCv,'main',0),'forward');assert.equal(flowBt.flowDirection,undefined);flowCv.segmentDirections={main:['reverse']};flowBt.flowDirection='reverse';const flowRoundtrip=M.readFile(JSON.parse(M.serializeFile(flowPlan)));assert.equal(M.segmentDirection(flowRoundtrip.objects[0],'main',0),'reverse');assert.equal(flowRoundtrip.objects[1].flowDirection,'reverse');const invalidFlow=M.clone(flowPlan);invalidFlow.objects[0].segmentDirections.main=['sideways'];assert.throws(()=>M.read(invalidFlow),/구간 진행 방향/);const invalidFlowLength=M.clone(flowPlan);invalidFlowLength.objects[0].segmentDirections.main=[];assert.throws(()=>M.read(invalidFlowLength),/구간 진행 방향/);
const old=JSON.parse(fs.readFileSync(require.resolve('./fixtures/floor-plan-v1.json'),'utf8').replace(/^\uFEFF/,'')),oldCopy=JSON.stringify(old),converted=M.read(old);assert.equal(converted.version,2);assert.equal(JSON.stringify(old),oldCopy);assert.equal(converted.objects.find(o=>o.kind==='W').rackTypeId,'');for(const o of old.objects){const n=converted.objects.find(v=>v.id===o.id);if(o.points){const xs=o.points.map(v=>v.x),ys=o.points.map(v=>v.y);assert.deepEqual(M.bounds(n),{x:Math.min(...xs),y:Math.min(...ys),w:Math.max(...xs)-Math.min(...xs)+o.width,h:Math.max(...ys)-Math.min(...ys)+o.width});}else assert.deepEqual([n.x,n.y,n.w,n.h],[o.x,o.y,o.w,o.h]);}assert.deepEqual(M.read(JSON.parse(JSON.stringify(converted))),converted);
const window={WmsFloorPlanModel:M,WMS_PUBLISHED_CONTENT:{storage:{menus:{menus:[{id:'editor-menu',viewType:'floorPlanEditor'}]}}}};vm.runInNewContext(fs.readFileSync(require.resolve('../js/floor-plan-editor'),'utf8'),{window});assert.equal(window.wmsFloorPlanEditor.isMenu({id:'editor-menu',viewType:'cards'}),true);assert.equal(window.wmsFloorPlanEditor.isMenu({id:'other',label:'평면도 에디터'}),false);
console.log('Floor plan v2: precision, path centerline, rotation, exact collision, rack capacity, tunnel alignment, legacy preservation, atomic history and isolated routing passed.');

assert.equal(M.formatMeters(4),'4.00');assert.equal(M.formatMeters(4.567),'4.57');assert.equal(M.formatMeters(1.005),'1.01');assert.equal(M.formatMeters(-.001),'0.00');assert.equal(M.roundMeters(8.456),8.46);const legacyPrecision=M.clone(p);legacyPrecision.objects[0].w=4.567;assert.equal(M.read(legacyPrecision).objects[0].w,4.567,'Existing saved precision is preserved; formatting never mutates it.');

const fittedPlan=M.blank();fittedPlan.rackTypes=[{id:'FIT-01',name:'맞춤 확인',bayWidth:1.1,depth:4.4,height:10,levels:10,levelHeight:1.45,depthCount:4}];const fittedRack={id:'W01',kind:'W',x:2,y:3,w:5.5,h:10.5,angle:0,rackTypeId:'FIT-01',bayGap:.1,rowGap:.66,margin:0,locked:false};fittedPlan.objects=[fittedRack];let fittedLayout=M.rackLayout(fittedRack,fittedPlan);assert.deepEqual([fittedLayout.bays,fittedLayout.rows,fittedLayout.actualW,fittedLayout.actualH],[4,2,4.7,9.46]);const fittedCenter=[fittedRack.x+fittedRack.w/2,fittedRack.y+fittedRack.h/2];M.fitRack(fittedRack,fittedPlan,4,2);assert.deepEqual([fittedRack.w,fittedRack.h],[4.7,9.46]);assert.deepEqual([fittedRack.x+fittedRack.w/2,fittedRack.y+fittedRack.h/2],fittedCenter);fittedRack.margin=.5;M.fitRack(fittedRack,fittedPlan,4,2);assert.deepEqual([fittedRack.w,fittedRack.h],[5.2,9.96]);fittedLayout=M.rackLayout(fittedRack,fittedPlan);assert.deepEqual([fittedLayout.bays,fittedLayout.rows,fittedLayout.margin,fittedLayout.remainingW,fittedLayout.remainingH],[4,2,.5,.5,.5]);assert.deepEqual(M.readFile(JSON.parse(M.serializeFile(fittedPlan))).objects[0],fittedRack,'Rack margin and calculated dimensions survive .gics roundtrip.');

const axisPlan=M.clone(p);axisPlan.objects[0].w=2.3;axisPlan.objects[0].h=1.7;axisPlan.objects[0].snapAnchor='center';assert.equal(M.read(axisPlan).objects[0].snapAnchor,'center');assert.deepEqual(M.axisPoint(axisPlan.objects[0]),{x:3.15,y:3.85});for(const key of M.axisKeys){const o={...axisPlan.objects[0],angle:35,snapAnchor:key};M.moveAxis(o,10,12);const point=M.axisPoint(o);assert.ok(Math.abs(point.x-10)<.001&&Math.abs(point.y-12)<.001);assert.equal(o.angle,35);assert.equal(o.w,2.3);}axisPlan.objects[0].snapAnchor='unknown';assert.throws(()=>M.read(axisPlan),/축 설정/);assert.deepEqual(M.read(p),p);const axisHistory=new M.History(p),axisChange=M.clone(p);axisChange.objects[0].snapAnchor='bottomRight';axisHistory.commit(axisChange);axisHistory.undo();assert.deepEqual(axisHistory.plan,p);axisHistory.redo();assert.equal(axisHistory.plan.objects[0].snapAnchor,'bottomRight');

const referencePlan=M.clone(p);referencePlan.objects[0].rackPreset={id:'PALLET-4L-DBL',w:4,h:3,bayGap:0,rowGap:0};assert.deepEqual(M.read(referencePlan),referencePlan,'Optional master reference round-trips without changing geometry.');const referenceHistory=new M.History(referencePlan),referenceEdit=M.clone(referencePlan);referenceEdit.objects[0].w=4.1;referenceHistory.commit(referenceEdit);referenceHistory.undo();assert.equal(referenceHistory.plan.objects[0].w,4);referenceHistory.redo();assert.equal(referenceHistory.plan.objects[0].rackPreset.w,4);for(const bad of [null,{id:'INVALID CODE',w:4,h:3,bayGap:0,rowGap:0},{id:'PALLET-4L',w:0,h:3,bayGap:0,rowGap:0},{id:'PALLET-4L',w:4,h:3,bayGap:-1,rowGap:0}]){const invalid=M.clone(p);invalid.objects[0].rackPreset=bad;assert.throws(()=>M.read(invalid));}assert.deepEqual(M.read(p),p,'Older documents receive no implicit reference metadata.');
