const assert = require('assert');
const fs = require('fs');
const path = require('path');
const vm = require('vm');

const root = path.resolve(__dirname, '..');
const sourcePath = path.join(root, 'index.html');
const source = fs.readFileSync(sourcePath, 'utf8');
const app = fs.readFileSync(path.join(root, 'js', 'app.js'), 'utf8');
const appFeatures = fs.readFileSync(path.join(root, 'js', 'app-features.js'), 'utf8').replace(/\r\n/g, '\n');
const rolePermissions = fs.readFileSync(path.join(root, 'js', 'role-permissions.js'), 'utf8');
const cardContentModel = fs.readFileSync(path.join(root, 'js', 'card-content-model.js'), 'utf8');
const testEditor = fs.readFileSync(path.join(root, 'js', 'test-editor-v14.js'), 'utf8');
const testEditorCss = fs.readFileSync(path.join(root, 'css', 'test-editor.css'), 'utf8');
const compatibilityPages = [
    'home.html', 'overview.html', 'floor.html', 'zone.html', 'rack.html',
    'editor.html', 'authoring.html', 'route.html', 'settings.html',
    'dashboard.html', 'models.html', 'simulations.html'
];

const expectedTabs = ['overview', 'floor', 'zone', 'rack', 'editor', 'route', 'settings', 'test'];
const actualTabs = [...source.matchAll(/<section id="view-([^"]+)"/g)].map((match) => match[1]);
assert.deepStrictEqual(actualTabs, expectedTabs, 'The menu panels changed unexpectedly.');

for (const asset of ['css/style.css', 'css/test-editor.css', 'js/role-permissions.js', 'js/card-content-model.js', 'js/app.js', 'js/app-features.js', 'js/test-editor-v14.js']) {
    assert.ok(fs.existsSync(path.join(root, asset)), `Missing runtime asset: ${asset}`);
}

for (const script of ['js/role-permissions.js', 'js/card-content-model.js', 'js/app.js', 'js/app-features.js', 'js/test-editor-v14.js']) {
    const code = fs.readFileSync(path.join(root, script), 'utf8');
    new vm.Script(code, { filename: script });
}

assert.ok(source.includes('data-role="viewer"'), 'The site must open in Viewer mode.');
assert.ok(source.includes('permissionStatusBtn'), 'The sidebar role status control is missing.');
assert.ok(source.includes('permissionModal'), 'The role selection dialog is missing.');
assert.ok(source.includes('id="loginScreen"'), 'The local login screen is missing.');
assert.ok(source.includes('data-brand-title="기획 템플릿"') && source.includes('data-brand-description="기획 배포 탬플릿 R&amp;D"'), 'Brand text must have one shared source of truth.');
assert.ok(source.includes('id="loginTitle"') && source.includes('id="sidebarTitle"') && source.includes('data-brand-field="title"'), 'Login and sidebar titles must share a brand field.');
assert.ok(source.includes('id="loginSubtitle"') && source.includes('id="sidebarSubtitle"') && source.includes('data-brand-field="description"'), 'Login and sidebar descriptions must share a brand field.');
assert.ok(source.includes('placeholder="아이디를 입력하세요."'), 'The login user ID placeholder is missing.');
assert.ok(source.includes('placeholder="비밀번호를 입력하세요."'), 'The login password placeholder is missing.');
assert.ok(source.includes('maxlength="8" pattern="[A-Za-z0-9]{8}"'), 'Login credentials must be limited to eight alphanumeric characters.');
assert.ok(source.includes('id="loginUserIdHint"') && source.includes('id="loginPasswordHint"'), 'Login fields must expose credential guidance.');
assert.ok(source.includes('id="loginSubmitBtn" type="submit" disabled'), 'The login button must start disabled.');
assert.ok(source.includes('id="logoutBtn"'), 'Logout must be available from the permission dialog.');
assert.ok(source.includes('id="logoutConfirmModal"'), 'Logout must require confirmation.');
assert.ok(source.includes('id="sidebarHelpBtn"') && source.includes('도움말'), 'The sidebar help button is missing.');
assert.ok(source.includes('id="helpModal"') && source.includes('id="helpModalTitle"'), 'The help dialog is missing.');
assert.ok(source.includes('id="helpConfirmBtn"'), 'The help dialog confirmation button is missing.');
assert.ok(source.includes('class="help-level1-toggle"') && source.includes('class="help-level2-toggle"'), 'The help dialog must expose two accordion levels.');
assert.ok(source.includes('aria-expanded="false" aria-controls="help-level1-screen"'), 'The screen composition help section must start collapsed.');
assert.ok(rolePermissions.includes("const userStorageKey = 'wms-local-login-user-v1'"), 'The local login user session key is missing.');
assert.ok(rolePermissions.includes('const isAuthenticated = () => Boolean(currentUserId);'), 'Login state must be explicit.');
assert.ok(rolePermissions.includes('const initializeBrandSync = () => {'), 'Brand text must synchronize on initialization.');
assert.ok(rolePermissions.includes("window.wmsBranding = {"), 'Brand text must expose a shared update path.');
assert.ok(rolePermissions.includes('if (document.body.dataset[dataKey] !== normalizedValue)'), 'Brand synchronization must not create recursive attribute updates.');
assert.ok(rolePermissions.includes('const loginCredentialPattern = /^[A-Za-z0-9]{8}$/;'), 'Login credentials must require exactly eight alphanumeric characters.');
assert.ok(rolePermissions.includes("field.value.replace(/[^A-Za-z0-9]/g, '').slice(0, 8)"), 'Login credentials must normalize pasted invalid characters.');
assert.ok(rolePermissions.includes('loginCredentialPattern.test(loginUserId.value) && loginCredentialPattern.test(loginPassword.value)'), 'Login activation must require two valid eight-character credentials.');
assert.ok(rolePermissions.includes("field.dataset.isComposing = 'true';"), 'Credential fields must detect Korean composition.');
assert.ok(rolePermissions.includes('한글 입력 중 — 영문으로 전환하세요'), 'Korean input state must be announced to the user.');
assert.ok(rolePermissions.includes('영문·숫자만 사용할 수 있습니다'), 'Invalid credential characters must be explained.');
assert.ok(rolePermissions.includes("hint.textContent = '입력 완료';"), 'Completed credentials must be announced.');
assert.ok(rolePermissions.includes("window.location.hash = '';"), 'Logout must clear the current route.');
assert.ok(app.includes('window.wmsPermissions?.isAuthenticated?.() !== true'), 'Routing must block unauthenticated menu access.');
assert.ok(source.includes('id="sidebarTitle"') && source.includes('기획 템플릿'), 'The sidebar title was not updated.');
assert.ok(source.includes('id="sidebarSubtitle"') && source.includes('기획 배포 탬플릿 R&amp;D'), 'The sidebar subtitle was not updated.');
assert.ok(source.includes('data-original-title="YUPOONG"'), 'The original sidebar logo label must remain recoverable.');
assert.ok(source.includes('data-original-subtitle="유풍 창고 관리 시스템(WMS)"'), 'The original sidebar subtitle must remain recoverable.');
assert.ok(testEditor.includes('permission-editor-only'), 'Card editing controls must be marked as Editor-only.');
assert.ok(source.includes('id="overviewCardList"'), 'The Overview card list is missing.');
assert.ok(source.includes('id="overviewAddCardBtn"'), 'The Overview card add button is missing.');
assert.ok(source.includes('id="authoringCardList"'), 'The Authoring card list is missing.');
assert.ok(source.includes('id="authoringAddCardBtn"'), 'The Authoring card add button is missing.');
assert.ok(source.includes('id="routeCardList"'), 'The Route card list is missing.');
assert.ok(source.includes('id="routeAddCardBtn"'), 'The Route card add button is missing.');
assert.ok(app.includes('overviewCardStorageKey'), 'Overview cards must use a dedicated storage key.');
assert.ok(app.includes('authoringCardStorageKey'), 'Authoring cards must use a dedicated storage key.');
assert.ok(app.includes('routeCardStorageKey'), 'Route cards must use a dedicated storage key.');
assert.ok(app.includes('migrateOverviewTableCards'), 'Legacy Overview table cards must be migrated.');
assert.ok(app.includes('migrateAuthoringTableCards'), 'Legacy Authoring table cards must be migrated.');
assert.ok(app.includes('structuredContent: true'), 'Overview cards must enable structured content editing.');
assert.ok(testEditor.includes('structuredContent = false'), 'Card editor content support must be configurable by menu.');
assert.ok(appFeatures.includes('const visibleTabIds = typeof getVisibleTabs === \'function\''), 'Search must be limited to currently visible menus.');
assert.ok(appFeatures.includes("!getVisibleTabs().includes(res.tabId)"), 'Search result navigation must recheck menu visibility.');
assert.ok(appFeatures.includes('function getSearchTabTitle(tabId)'), 'Search badges must resolve dynamic menu labels.');
assert.ok(appFeatures.includes('function openHelpModal()'), 'The help modal open handler is missing.');
assert.ok(appFeatures.includes('function closeHelpModal()'), 'The help modal close handler is missing.');
assert.ok(appFeatures.includes('function initializeHelpAccordion()'), 'The help accordion initialization is missing.');
assert.ok(appFeatures.includes('function collapseAllHelpSections()'), 'The help dialog must reset all accordion sections when it opens.');
assert.ok(appFeatures.includes('collapseAllHelpSections();'), 'The help dialog must collapse all sections before opening.');
assert.ok(appFeatures.includes("helpModal.querySelectorAll('.help-level1-toggle')"), 'Level 1 help toggles must be initialized.');
assert.ok(appFeatures.includes("helpModal.querySelectorAll('.help-level2-toggle')"), 'Level 2 help toggles must be initialized.');
assert.ok(!appFeatures.includes("helpModal.querySelectorAll('.help-level1-toggle').forEach((otherButton)"), 'Opening one Level 1 help item must not close other items.');
assert.ok(appFeatures.includes('.test-card-body-text'), 'Search must include shared card editor content.');
assert.ok(appFeatures.includes('function canRegisterUpdate()'), 'Update registration must have an explicit permission guard.');
assert.ok(appFeatures.includes('window.wmsPermissions?.isAuthenticated?.() === true && window.wmsPermissions?.isEditor?.() === true'), 'Update registration must require an authenticated Editor.');
assert.ok(appFeatures.includes("window.addEventListener('wms-role-change'"), 'Update registration must hide when the role changes.');
assert.ok(appFeatures.includes("window.addEventListener('wms-auth-change'"), 'Update registration must hide when authentication changes.');
assert.ok(appFeatures.includes('if (!canRegisterUpdate()) {\n            closeUpdateRegisterModal();'), 'Update registration submission must be permission-guarded.');
assert.ok(testEditor.includes("editLocked: card.dataset.editLocked === 'true'"), 'Card edit locks must be persisted.');
assert.ok(testEditor.includes("block.type === 'diagram'"), 'Read-only diagram cards must be rendered.');

assert.ok(!testEditor.includes('data-card-type="left-right"'), 'Left 1 / right 2 must not be offered as a new card type.');
assert.ok(testEditor.includes('data-card-type="single"'), 'Single-column card type was removed.');
assert.ok(testEditor.includes('data-card-type="double"'), 'Two-column card type was removed.');
assert.ok(testEditor.includes('data-card-type="triple"'), 'Three-column card type was removed from the test menu.');
assert.ok(testEditor.includes("type === 'triple'"), 'Three-column card creation was removed.');
assert.ok(testEditor.includes('test-card-row-triple'), 'Three-column card layout was removed.');
assert.ok(testEditor.includes('supportsTripleCards = false'), 'Three-column cards must be enabled by menu capability.');
assert.ok(app.includes('supportsTripleCards: true'), 'Custom menus must inherit the test menu three-column card capability.');
assert.ok(app.includes('structuredContent: true'), 'Custom menus must inherit the test menu structured card editor.');
assert.ok(testEditor.includes('migrateLegacyCardsToStructuredContent'), 'Legacy custom cards must migrate to structured content blocks.');
assert.ok(testEditor.includes("field.addEventListener('compositionend'"), 'Body editor must handle IME composition completion.');
assert.ok(testEditor.includes("event.code === 'Enter'"), 'IME Enter detection must support Process-key events with an Enter code.');
assert.ok(testEditor.includes('event.keyCode === 229'), 'IME processing key events must be recognized.');
assert.ok(testEditor.includes('event.which === 229'), 'Legacy IME processing key events must be recognized.');
assert.ok(testEditor.includes('pendingCompositionEnter'), 'The body editor must remember an Enter used to finish Korean IME composition.');
assert.ok(testEditor.includes('getBodyLineBreakState'), 'IME Enter handling must compare the logical line state before and after composition completion.');
assert.ok(testEditor.includes('currentState.textBreakCount > pendingEnter.state.textBreakCount'), 'A text newline inserted by the browser must prevent a duplicate fallback line break.');
assert.ok(testEditor.includes('currentState.visualBreakCount > pendingEnter.state.visualBreakCount'), 'A visual contenteditable newline inserted by the browser must prevent a duplicate fallback line break.');
assert.ok(testEditor.includes('pendingEnter.sequence !== compositionEnterSequence'), 'Each physical IME Enter must have a single active fallback sequence.');
assert.ok(testEditor.includes('if (!browserInsertedLineBreak) insertBodyLineBreak();'), 'IME composition Enter must add one line break when the browser only commits the composition.');
assert.ok(!testEditor.includes("field.querySelector('br:not([data-test-line-break-filler])')"), 'IME newline detection must not depend on BR markup alone.');
assert.ok(!testEditor.includes("/<div(?:\\s|>)/i.test(field.innerHTML)"), 'IME newline detection must not depend on DIV markup alone.');
assert.ok(testEditor.includes("bodyLineBreakFillerSelector = 'br[data-test-line-break-filler]'"), 'A plain trailing line break must have a temporary visual filler.');
assert.ok(testEditor.includes('const hasTrailingContent = end < getBodyValue().length;'), 'Plain Enter must detect content after the caret.');
assert.ok(testEditor.includes('if (!hasTrailingContent) {'), 'The visual line-break filler must only be added at the end of the body.');
assert.ok(testEditor.includes('const renumberEdits = [];'), 'Inserting a numbered line must collect following number-prefix updates.');
assert.ok(testEditor.includes('followingNumbered[1] === targetIndent'), 'Only following numbered lines at the inserted line level may be renumbered.');
assert.ok(testEditor.includes('renumberEdits.reverse().forEach'), 'Following number prefixes must be updated from the end to preserve offsets.');
assert.ok(testEditor.includes('setBodySelection(insertedCaret, insertedCaret);'), 'Renumbering must restore the caret to the inserted numbered line.');
assert.ok(testEditor.includes('const renumberFollowingTopLevelItems ='), 'Top-level number removal must renumber later items.');
assert.ok(testEditor.includes('const topLevelListItem = /^(\\d+\\.|[•◦-])\\s/.exec'), 'Top-level Shift+Tab must detect numbered and bullet lines.');
assert.ok(testEditor.includes("replaceBodyRange(lineStart, lineStart + removedPrefixLength, '');"), 'Top-level Shift+Tab must remove only the list prefix.');
assert.ok(testEditor.includes("const previousNumberedLine = value.slice(0, startOffset).split('\\n').reverse()"), 'Top-level renumbering must continue from the previous same-level number.');
assert.ok(testEditor.includes("return line.replace(/^(\\d+\\.|[•◦-])\\s/, '');"), 'Selected top-level list lines must become plain text.');
assert.ok(testEditor.includes('html: getStoredBodyHtml(slot.field)'), 'Temporary line-break fillers must not be saved in structured card HTML.');
assert.ok(testEditor.includes('getTextBeforeBodyLineBreakFiller'), 'Stale line-break fillers must be detected from actual DOM text order.');
assert.ok(testEditor.includes("if (!isCompositionKey && (isEnterKey || event.key === 'Tab')) removeBodyLineBreakFillers();"), 'Text and IME input must keep the empty-line filler until content is inserted.');
assert.ok(!testEditor.includes('const editsBody ='), 'Generic keydown handling must not remove the empty-line filler before text insertion.');
assert.ok(testEditor.includes('test-format-toolbar-close'), 'The text format toolbar must provide an explicit close button.');
assert.ok(testEditor.includes('closeFormatToolbarOnOutsidePointerDown'), 'The text format toolbar must close when clicking outside it.');
assert.ok(testEditor.includes('closeFormatToolbarOnSelectionChange'), 'The text format toolbar must close when its text selection is cleared.');
assert.ok(testEditor.includes('closeFormatToolbarForContextChange'), 'The text format toolbar must close when the editing context changes.');
assert.ok(!/field\.addEventListener\('compositionstart',[\s\S]{0,180}removeBodyLineBreakFillers\(\);/.test(testEditor), 'IME composition start must not remove the empty-line filler.');
assert.ok(!testEditor.includes("field.addEventListener('beforeinput'"), 'Body editing must not cancel the browser-native IME line break.');
assert.ok(!testEditor.includes("field.addEventListener('keyup'"), 'Body editing must not add a delayed IME line-break fallback.');
assert.ok(!testEditor.includes('spellcheck="false"'), 'Card editor text inputs must allow browser spellcheck.');
assert.ok(!testEditor.includes('field.spellcheck = false'), 'Dynamically added body fields must allow browser spellcheck.');
assert.ok(testEditor.includes("type === 'left-right'"), 'Saved left 1 / right 2 cards must remain backward compatible.');
assert.ok(/try \{\r?\n                onChange\(rows\);/.test(testEditor), 'Card storage failures must not interrupt the editor flow.');
assert.ok(testEditor.includes("error?.name === 'QuotaExceededError'"), 'Quota storage warning handling was removed.');
assert.ok(testEditor.includes('indexedDB.open(imageDatabaseName, 1)'), 'Card images must use IndexedDB storage.');
assert.ok(testEditor.includes('migrateLegacyCardImages(initialRows)'), 'Legacy card images must migrate to IndexedDB.');
assert.ok(testEditor.includes('imageId: card.dataset.imageId ||'), 'Card metadata must store an image ID instead of image data.');
assert.ok(testEditor.includes("bodyType: card.dataset.bodyType || 'text'"), 'Text body type compatibility was removed.');
assert.ok(testEditor.includes('test-table-editor'), 'Table body editor was removed.');
assert.ok(testEditor.includes('최초 등록 후 본문 타입은 변경할 수 없습니다.'), 'Body type lock guidance was removed.');
assert.ok(testEditor.includes('renderTestTable(body, tableData)'), 'First saved table rendering was removed.');
assert.ok(testEditor.includes('renderTestTable(body2, tableData2)'), 'Second saved table rendering was removed.');
assert.ok(testEditor.includes('Array.from(row.children).forEach((cell, columnIndex) => {'), 'Every table cell must expose resize handles.');
assert.ok(!testEditor.includes('if (rowIndex === 0) Array.from(row.children)'), 'Column resizing must not be limited to the first row.');
assert.ok(testEditor.includes('const setTableColumnCount = (nextColumns) => {'), 'Table column count changes must preserve width data.');
assert.ok(testEditor.includes('const retainedWidth = 100 - (addedColumnWidth * (targetColumns - currentColumns));'), 'New columns must shrink existing widths proportionally.');
assert.ok(testEditor.includes('const tableCellMinimumWidth = 36;'), 'Table cells must support the reduced 36px minimum width.');
assert.ok(testEditor.includes('const adjacentIndex = columnIndex === columnCount - 1 ? columnIndex - 1 : columnIndex + 1;'), 'The last table column must resize against its adjacent column.');
assert.ok(testEditor.includes("columnHandle.classList.add('is-last-column')"), 'The last column must expose its left resize boundary.');
assert.ok(testEditor.includes("document.createElement('textarea')"), 'Table cells must use multiline textareas.');
assert.ok(testEditor.includes('const resizeTableRowForContent = (rowIndex) => {'), 'Table rows must grow for multiline cell content.');
assert.ok(testEditorCss.includes('white-space: pre-wrap;'), 'Saved table cells must preserve line breaks.');
assert.ok(testEditor.includes('hasFirstColumnHeader'), 'First-column header table data was removed.');
assert.ok(testEditor.includes('test-table-first-column-header-input'), 'First-column header control was removed.');
assert.ok(testEditor.includes("const isFirstColumnHeader = Boolean(data.hasFirstColumnHeader) && columnIndex === 0;"), 'Saved first-column headers must render independently.');
assert.ok(testEditor.includes('Math.max(0, ...tableData.rows.map((row) => row.length), 1)'), 'Tables must support a minimum size of 1 × 1.');
assert.ok(testEditor.includes('test-table-title-input'), 'Table title editing control was removed.');
assert.ok(testEditor.includes('captionText.textContent = data.title;'), 'Saved table titles must render as table captions.');
assert.ok(testEditor.includes("tableData.title = typeof tableData.title === 'string' ? tableData.title.slice(0, 80) : '';"), 'Table title compatibility handling was removed.');
assert.ok(testEditor.includes('test-card-table-caption-icon'), 'Table title icon was removed.');
assert.ok(testEditor.includes('test-body-editor-panel'), 'Body editor panels were removed.');
assert.ok(testEditor.includes('test-edit-content-blocks'), 'Dynamic content block container was removed.');
assert.ok(testEditor.includes('contentBlocks'), 'Content block storage was removed.');
assert.ok(source.indexOf('js/card-content-model.js') < source.indexOf('js/app.js'), 'The card content model must load before application initialization.');
assert.ok(cardContentModel.includes('function registerBlockType(definition)'), 'Future card block formats must use the shared registry.');
assert.ok(cardContentModel.includes("aliases: ['plainText', 'text2']"), 'Legacy text aliases must be confined to the compatibility model.');
assert.ok(cardContentModel.includes('formatVersion: Math.max(textFormatVersion'), 'Canonical Text blocks must include an explicit format version without downgrading future data.');

const cardContentContext = { window: {} };
vm.createContext(cardContentContext);
new vm.Script(cardContentModel, { filename: 'js/card-content-model.js' }).runInContext(cardContentContext);
const runtimeContentModel = cardContentContext.window.wmsCardContentModel;
for (const legacyType of ['plainText', 'text', 'text2']) {
    const legacyBlock = { type: legacyType, text: 'preserved', html: '<b>preserved</b>' };
    const normalizedBlock = runtimeContentModel.normalizeBlock(legacyBlock);
    assert.strictEqual(normalizedBlock.type, 'text', `${legacyType} must be read as canonical Text.`);
    assert.strictEqual(normalizedBlock.formatVersion, 2, `${legacyType} must use Text format version 2 in the editor.`);
    assert.strictEqual(normalizedBlock.text, 'preserved', `${legacyType} text must be preserved.`);
    assert.strictEqual(normalizedBlock.html, '<b>preserved</b>', `${legacyType} HTML must be preserved.`);
    assert.strictEqual(legacyBlock.type, legacyType, `${legacyType} source data must not be rewritten while loading.`);
}
assert.strictEqual(runtimeContentModel.normalizeEditorType('text2'), 'text', 'Legacy body types must select the visible Text option.');
assert.strictEqual(runtimeContentModel.normalizeEditorType('table'), 'table', 'Table body types must remain tables.');
const futureTextBlock = runtimeContentModel.normalizeBlock({ type: 'text', formatVersion: 3, text: 'future' });
assert.strictEqual(futureTextBlock.formatVersion, 3, 'Future Text versions must not be downgraded while reading.');
assert.strictEqual(runtimeContentModel.isEditableBlock(futureTextBlock), false, 'Unsupported future Text versions must remain read-only.');
assert.ok(testEditor.includes('const contentModel = window.wmsCardContentModel;'), 'The shared editor must use the card content model.');
assert.ok(!testEditor.includes('contentModel.migrateRows'), 'Opening a page must not persist text-format migration automatically.');
assert.ok(testEditor.includes('test-add-pdf-block'), 'PDF add button was removed.');
assert.ok(testEditor.includes("type: 'pdf', pdfId"), 'PDF block metadata must be saved.');
assert.ok(testEditor.includes('openOriginalPdf'), 'PDF original viewer was removed.');
assert.ok(testEditorCss.includes('.test-card-pdf-frame'), 'PDF card preview styles are missing.');
assert.ok(testEditor.includes('test-add-google-drive-block'), 'Google Drive document add button was removed.');
assert.ok(testEditor.includes('parseGoogleDriveDocumentUrl'), 'Google Drive URL validation was removed.');
assert.ok(testEditor.includes('openGoogleDriveDocument'), 'Google Drive document viewer was removed.');
assert.ok(testEditorCss.includes('.test-card-google-drive-frame'), 'Google Drive card preview styles are missing.');
assert.ok(testEditor.includes('data-body-type="text">Text'), 'The single visible Text body type option is missing.');
assert.ok(!testEditor.includes('data-body-type="text2"'), 'The temporary Text 2 UI type must be removed.');
assert.ok(testEditor.includes('data-body-type="table">Table'), 'The Table body type option must be displayed as Table.');
assert.ok(!testEditor.includes("'text2'"), 'The editor runtime must not branch on the temporary Text 2 storage type.');
assert.ok(testEditor.includes('const isRichTextBodyField'), 'The canonical Text editor state check is missing.');
assert.ok(testEditor.includes('const getRichTextNumberMarker'), 'Canonical Text numbering rules are missing.');
assert.ok(testEditor.includes("return `${toRichTextAlphabetic(sequence)}.`;"), 'Second-level numbering must use alphabetic markers.');
assert.ok(testEditor.includes("return `${toRichTextRoman(sequence)}.`;"), 'Third-level numbering must use Roman numeral markers.');
assert.ok(testEditor.includes('if (!shiftKey && level >= 2) return true;'), 'Numbered lists must stop indenting at the third level.');
assert.ok(testEditor.includes("const getRichTextBulletMarker = (level) => ['•', '◦', '-']"), 'Text bullet indentation must retain three levels.');
assert.ok(testEditor.includes('const insertRichTextBulletLineBreak'), 'Text bullet lists must continue with Enter.');
assert.ok(testEditor.includes('const handleRichTextBulletIndent'), 'Text bullet lists must handle Tab and Shift+Tab.');
assert.ok(testEditor.includes("bulletPicker.innerHTML = '<button type=\"button\" data-bullet=\"number\">1</button><button type=\"button\" data-bullet=\"•\">•</button>';"), 'The Text slash picker must show only number and primary bullet choices.');
assert.ok(testEditor.includes("const numberMarker = '(?:\\\\d+|[a-z]+|[ivxlcdm]+)\\\\.';"), 'The Text viewer must recognize nested numbering markers.');
assert.ok(testEditor.includes("const bulletMarker = '[•◦▪-]';"), 'The Text viewer must recognize nested bullet markers.');
assert.ok(testEditor.includes('contentModel.createTextBlock'), 'Copy and save paths must emit canonical Text blocks.');
assert.ok(testEditor.includes('test-add-image-block'), 'Image add button was removed.');
assert.ok(testEditor.includes('hasUnsupportedCardContent'), 'Unsupported card content must lock editing.');
assert.ok(!testEditor.includes("imageBlock.panel.querySelector('input')?.click();"), 'Adding an image block must not open the file chooser automatically.');
assert.ok(testEditor.includes('test-add-body-block'), 'Body add button was removed.');
assert.ok(testEditor.includes('test-card-move-up-btn'), 'Card move-up button was removed.');
assert.ok(testEditor.includes('test-card-move-down-btn'), 'Card move-down button was removed.');
assert.ok(testEditor.includes('function setupResizableRow'), 'Two- and three-column card width resizing was removed.');
assert.ok(testEditor.includes('columnWidths: row.dataset.columnWidths'), 'Card-row width ratios must be persisted.');
assert.ok(testEditor.includes('test-card-column-resize-handle'), 'Card-row resize handles were removed.');
assert.ok(testEditor.includes('new ResizeObserver(scheduleHandlePosition)'), 'Card width handles must follow container size changes.');
assert.ok(testEditorCss.includes('.test-card-column-resize-handle'), 'Card-row resize handle styles are missing.');
assert.ok(testEditor.includes('function moveCardOneStep'), 'Individual card ordering was removed.');
assert.ok(testEditor.includes('getCardsInReadingOrder()'), 'Cross-layout card reading order was removed.');
assert.ok(testEditor.includes("scrollIntoView({ behavior: 'smooth', block: 'center', inline: 'center' })"), 'Moved cards must be centered in the viewport.');
assert.ok(!testEditor.includes('test-card-order-menu'), 'The old card order dropdown must not return.');
assert.ok(testEditor.includes('test-card-reorder-toolbar'), 'Fixed card reorder controls were removed.');
assert.ok(testEditor.includes('function closeFixedCardReorder'), 'Fixed reorder event cleanup was removed.');
assert.ok(testEditor.includes("keyEvent.key !== 'Escape'"), 'Fixed reorder controls must close with Escape.');
assert.ok(testEditor.includes('renderTestText(title, card.dataset.title ||'), 'Content-block cards must render saved headers.');
assert.ok(testEditor.includes('slot.blockOrder = blockOrder;'), 'Content-block editing must retain saved block order.');
assert.ok(testEditorCss.includes('.test-card-content-block-text'), 'Content-block text rendering styles were removed.');
assert.ok(fs.readFileSync(path.join(root, 'css', 'style.css'), 'utf8').includes('.help-modal'), 'Help modal styles are missing.');
assert.ok(fs.readFileSync(path.join(root, 'css', 'style.css'), 'utf8').includes('.help-accordion'), 'Help accordion styles are missing.');
assert.ok(fs.readFileSync(path.join(root, 'css', 'style.css'), 'utf8').includes('overscroll-behavior: contain'), 'Help content must scroll independently within the dialog.');
assert.ok(fs.readFileSync(path.join(root, 'css', 'style.css'), 'utf8').includes('height: min(760px, calc(100dvh - 2rem))'), 'Help dialog must reserve a fixed viewport-bound scroll area.');
assert.ok(fs.readFileSync(path.join(root, 'css', 'style.css'), 'utf8').includes('.help-accordion > .help-level1 + .help-level1'), 'Expanded help sections must push later sections downward.');
assert.ok(!testEditorCss.includes('.text2-list-picker'), 'Removed Text 2 list-picker styles must not remain.');
assert.ok(!testEditorCss.includes('.text2-format-toolbar'), 'Removed Text 2 toolbar styles must not remain.');
assert.ok(!testEditorCss.includes('.test-card-content-block-plainText'), 'Removed Text 2 card styles must not remain.');
assert.ok(testEditorCss.includes('object-fit: contain;'), 'Content-block images must preserve their full aspect ratio.');
assert.ok(testEditor.includes("imageFrame.className = 'test-card-image-frame'"), 'Each structured image must have its own original-view frame.');
assert.ok(testEditor.includes('class="test-card-image-frame"'), 'Legacy card images must use the same original-view frame.');
assert.ok(testEditorCss.includes('.test-card-image-frame:focus-within .test-original-view-btn'), 'Original-view buttons must remain available while focused.');
assert.ok(testEditorCss.includes('.test-card-has-description .test-card-content-blocks'), 'A card description must have clear separation from its first structured content block.');
assert.ok(testEditorCss.includes('.test-card-has-description .test-card-image-slot'), 'A card description must have clear separation from its image content.');
assert.ok(testEditorCss.includes('.test-card-has-description .test-card-body-columns'), 'A card description must have clear separation from its text or table content.');
assert.ok(testEditorCss.includes('gap: 1rem;'), 'Card content blocks must retain readable separation.');
assert.ok(testEditor.includes('function renderTestListBody'), 'Card list display renderer was removed.');
assert.ok(testEditorCss.includes('.test-card-body-list-line'), 'Hanging list-line layout styles were removed.');
assert.ok(testEditor.includes('const bodySlots = [primarySlot'), 'Body editor state must remain slot-specific.');
assert.ok(testEditor.includes('slot.tableEditor = slotTableEditor;'), 'Each body slot must own its table editor.');
assert.ok(testEditor.includes('initialValues.tables.some(Boolean)'), 'Table cards must retain the delete confirmation check.');
assert.ok(testEditor.includes('test-card-edit-copy'), 'Card copy action was removed from the edit dialog.');
assert.ok(testEditor.includes('test-card-edit-paste'), 'Empty-card paste action was removed from the edit dialog.');
assert.ok(testEditor.includes("cardClipboardStorageKey = 'wms-test-card-clipboard-v1'"), 'Structured card clipboard persistence was removed.');
assert.ok(testEditor.includes('clipboardSource: Boolean(savedBlock?.clipboardSource)'), 'Pasted images must remain distinguishable from saved card images.');
assert.ok(testEditor.includes("imageState.file || (imageState.clipboardSource && imageState.imageId)"), 'Pasted images must be cloned into independent card image IDs.');
assert.ok(testEditor.includes('!cardHasStoredContent(card)'), 'Paste must remain restricted to empty cards.');
assert.ok(testEditorCss.includes('.test-card-edit-paste'), 'Card paste button styling was removed.');
assert.ok(testEditorCss.includes('.test-card-edit-copy'), 'Card copy button styling was removed.');

assert.ok(appFeatures.includes('split(/\\s+/)'), 'Search keywords must split on whitespace.');
assert.ok(appFeatures.includes('replace(/\\s+/g,'), 'Search text must normalize whitespace.');
assert.ok(!appFeatures.includes("searchResultsList.innerHTML = '<div class=\"search-result-no-match\">"), 'Search input must not be inserted through innerHTML.');

assert.ok(/<script src="js\/app\.js(?:\?[^\"]*)?"><\/script>/.test(source), 'Router entry was removed.');
assert.ok(/<script src="js\/app-features\.js(?:\?[^\"]*)?"><\/script>/.test(source), 'Shared feature entry was removed.');
assert.ok(/<script src="js\/test-editor-v14\.js(?:\?[^\"]*)?"><\/script>/.test(source), 'Test editor entry was removed.');
assert.ok(source.includes('id="testCardList"'), 'Test card list was removed.');
assert.ok(source.includes('id="testAddCardBtn"'), 'Test card add button was removed.');

for (const page of compatibilityPages) {
    const content = fs.readFileSync(path.join(root, page), 'utf8');
    assert.strictEqual(content, source, `${page} is out of sync with index.html.`);
}

console.log('Structure regression checks passed.');
